### ISSUE TITLE
Install and style plugin for inline commenting

### ISSUE THREAD

**Issue by libby-barker** [humanmade/hm-handbook-theme#68] opened 2016-11-03 19:48 UTC
This commenting will be used to gather feedback from public

**Comment by mattheu** [comment] 2016-11-08 09:56
I'm going to propsoe we close this issue as a duplicate of ttps://github.com/humanmade/hm-handbook-theme/issues/10.

I originally decided that whilst it's a nice to have, this needn't be a blocker to the public release. I implemented standard comments instead.

If someone wants to tackle this, then great. However I'd like to see it done well. The old handbook just used a plugin but I didn't think it was great and was pretty buggy. Perhaps there are alternatives approaches as I realize doing something custom is a fair bit of work?

**Comment by mattheu** [comment] 2016-11-08 10:06
Additionally, I think we discussed having comments closed/hidden from the public, and instead drive questions to us via different channels. 

I also think it would be confusing to have both internal and external comments on this. 

Perhaps we need to discuss this further.

**Closed** 2016-11-11 11:45 UTC
Labels: duplicate
